# Generated by Django 5.0.6 on 2024-06-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_is_admin_user_is_stuff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_stuff",
            new_name="is_staff",
        ),
    ]
