# Generated by Django 5.0.6 on 2024-07-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_is_stuff_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
