# Generated by Django 5.2.1 on 2025-05-29 10:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantScoreTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("primary", models.IntegerField()),
                ("secondary", models.IntegerField()),
            ],
            options={
                "verbose_name": "Таблица первичных и вторичных баллов",
                "verbose_name_plural": "Таблицы первичных и вторичных баллов",
                "db_table": "variant_score_table",
            },
        ),
        migrations.CreateModel(
            name="UserVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "not_started"),
                            ("started", "started"),
                            ("completed", "completed"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("generated", models.BooleanField(default=False)),
                (
                    "complexity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ("result", models.IntegerField(default=None, null=True)),
                ("tasks", models.ManyToManyField(to="tasks.usertask")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
                "db_table": "user_variant",
                "ordering": ("-completed_at", "started_at"),
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("school", "School"), ("exam", "Exam")],
                        default="school",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Год, когда был этот вариант на экзамене",
                        null=True,
                    ),
                ),
                ("tasks", models.ManyToManyField(to="tasks.task")),
            ],
            options={
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
                "db_table": "variant",
            },
        ),
    ]
