# Generated by Django 5.0.6 on 2024-06-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservariant",
            options={"ordering": ("-completed_at", "started_at")},
        ),
    ]
