# Generated by Django 5.0.6 on 2024-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0002_alter_uservariant_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservarianttask",
            name="answer",
            field=models.JSONField(null=True),
        ),
    ]
