# Generated by Django 5.0.6 on 2024-07-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0003_alter_uservarianttask_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservariant",
            options={
                "ordering": ("-completed_at", "started_at"),
                "verbose_name": "Вариант",
                "verbose_name_plural": "Варианты",
            },
        ),
        migrations.AlterModelOptions(
            name="uservarianttask",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelOptions(
            name="variant",
            options={"verbose_name": "Вариант", "verbose_name_plural": "Варианты"},
        ),
    ]
