# Generated by Django 5.0.6 on 2024-07-21 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0004_alter_uservariant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservarianttask",
            name="variant",
        ),
        migrations.AddField(
            model_name="uservariant",
            name="tasks",
            field=models.ManyToManyField(to="variants.uservarianttask"),
        ),
        migrations.CreateModel(
            name="GeneratedUserVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("tasks", models.ManyToManyField(to="variants.uservarianttask")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный вариант",
                "verbose_name_plural": "Сгенерированные варианты",
                "db_table": "generated_user_variant",
            },
        ),
    ]
