# Generated by Django 5.0.6 on 2024-07-21 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0005_remove_uservarianttask_variant_uservariant_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateduservariant",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
            preserve_default=False,
        ),
    ]
