# Generated by Django 5.0.6 on 2024-07-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0006_generateduservariant_complexity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservariant",
            name="variant",
        ),
        migrations.AddField(
            model_name="uservariant",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uservariant",
            name="title",
            field=models.CharField(default="Some title", max_length=255),
            preserve_default=False,
        ),
    ]
