# Generated by Django 5.0.6 on 2024-07-22 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0007_remove_uservariant_variant_uservariant_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservariant",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
            preserve_default=False,
        ),
    ]
