# Generated by Django 5.0.6 on 2024-07-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0008_uservariant_complexity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneratedUserVariant",
        ),
    ]
