# Generated by Django 5.0.6 on 2024-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0009_delete_generateduservariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservariant",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "not_started"),
                    ("started", "started"),
                    ("completed", "completed"),
                ],
                default="not_started",
                max_length=15,
            ),
        ),
    ]
