# Generated by Django 5.0.6 on 2024-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("variants", "0011_variantscoretable_uservariant_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservariant",
            name="tasks",
            field=models.ManyToManyField(to="tasks.usertask"),
        ),
        migrations.AlterField(
            model_name="variant",
            name="tasks",
            field=models.ManyToManyField(to="tasks.task"),
        ),
        migrations.DeleteModel(
            name="UserVariantTask",
        ),
    ]
