# Generated by Django 5.0.7 on 2024-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0012_alter_uservariant_tasks_alter_variant_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='type',
            field=models.CharField(choices=[('school', 'School'), ('exam', 'Exam')], default='school', max_length=20),
        ),
        migrations.AddField(
            model_name='variant',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Год, когда был этот вариант на экзамене', null=True),
        ),
    ]
