# Generated by Django 5.0.6 on 2024-07-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
