# Generated by Django 5.0.7 on 2024-07-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_userscheduleconfig_delete_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserScheduleConfig',
        ),
    ]
