# Generated by Django 5.0.6 on 2024-06-19 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordreset",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 19, 9, 11, 51, 467461, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
