# Generated by Django 5.2.1 on 2025-05-29 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название задачи не будет нигде отображаться. Оно служит лишь для удобства поиска и выбора задач.",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Текст в формате Markdown. Также текст поддерживает синтаксис LaTeX.",
                        verbose_name="Содержание",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        help_text="Если тип ответа на задачу: Файл, то указывать не нужно.",
                        null=True,
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Текст"), ("F", "Файл")],
                        default="A",
                        max_length=1,
                        verbose_name="Тип ответа на задание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("file", models.FileField(upload_to="files", verbose_name="Файл")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл задачи",
                "verbose_name_plural": "Файлы задач",
                "db_table": "task_file",
            },
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "answer",
                    models.CharField(blank=True, null=True, verbose_name="Ответ"),
                ),
                (
                    "answer_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="user_task_answers/",
                        verbose_name="Файл ответа",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=None, null=True, verbose_name="Верно"),
                ),
                (
                    "is_skipped",
                    models.BooleanField(default=False, verbose_name="Пропущен"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="lessons.userlesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача пользователя",
                "verbose_name_plural": "Задачи пользователя",
                "db_table": "user_task",
            },
        ),
    ]
