# Generated by Django 5.0.6 on 2024-07-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="task",
        ),
        migrations.AlterModelTable(
            name="taskfile",
            table="task_file",
        ),
        migrations.AlterModelTable(
            name="usertask",
            table="user_task",
        ),
    ]
