# Generated by Django 5.0.7 on 2024-12-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_table_alter_taskfile_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertask",
            options={
                "verbose_name": "Задача пользователя",
                "verbose_name_plural": "Задачи пользователя",
            },
        ),
    ]
