# Generated by Django 5.0.7 on 2025-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_usertask_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("A", "Any"), ("T", "Table"), ("F", "File")],
                default="A",
                max_length=1,
            ),
        ),
    ]
