# Generated by Django 5.0.7 on 2025-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="task",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="task",
            name="kim_number",
        ),
        migrations.AddField(
            model_name="usertask",
            name="answer_file",
            field=models.FileField(
                blank=True, null=True, upload_to="user_task_answers/"
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="answer",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
