# Generated by Django 5.0.7 on 2025-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_complexity_remove_task_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.JSONField(null=True),
        ),
    ]
