# Generated by Django 5.0.7 on 2025-05-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
