# Generated by Django 5.0.7 on 2025-05-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_task_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("A", "Any"), ("F", "File")], default="A", max_length=1
            ),
        ),
    ]
