# Generated by Django 5.0.7 on 2025-05-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="answer",
            field=models.CharField(blank=True, null=True),
        ),
    ]
