# Generated by Django 5.0.7 on 2025-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_usertask_lesson_usertask_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskfile",
            options={
                "verbose_name": "Файл задачи",
                "verbose_name_plural": "Файлы задач",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(
                default="Untitled",
                help_text="Название задачи не будет нигде отображаться. Оно служит лишь для удобства поиска и выбора задач.",
                max_length=255,
                verbose_name="Название",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(
                help_text="Текст в формате Markdown. Также текст поддерживает синтаксис LaTeX.",
                verbose_name="Содержание",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                help_text="Если тип ответа на задачу: Файл, то указывать не нужно.",
                null=True,
                verbose_name="Правильный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("A", "Текст"), ("F", "Файл")],
                default="A",
                max_length=1,
                verbose_name="Тип ответа на задание",
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="file",
            field=models.FileField(upload_to="files", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
