# Generated by Django 5.0.7 on 2025-05-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0042_alter_lessonfile_options_alter_lesson_author_and_more"),
        ("tasks", "0012_alter_taskfile_options_task_name_alter_task_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="answer",
            field=models.CharField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="answer_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user_task_answers/",
                verbose_name="Файл ответа",
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="is_correct",
            field=models.BooleanField(default=None, null=True, verbose_name="Верно"),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="is_skipped",
            field=models.BooleanField(default=False, verbose_name="Пропущен"),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="lessons.userlesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
