# Generated by Django 5.0.6 on 2024-07-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="user",
        ),
    ]
