# Generated by Django 5.0.7 on 2024-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='active_before',
            field=models.DateField(default=None, null=True),
        ),
    ]
