# Generated by Django 5.0.7 on 2024-08-10 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_usersubscription_active_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='advantages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), default=['опПоддержка 24/7Э'], size=None),
            preserve_default=False,
        ),
    ]
