# Generated by Django 5.0.7 on 2024-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_advantages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='active_before',
            new_name='expires_at',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='canceled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[(0, 'active'), (1, 'canceled')], default='active', max_length=10),
        ),
    ]
