# Generated by Django 5.0.7 on 2025-01-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0007_rename_active_before_usersubscription_expires_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="with_home_work",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
