# Generated by Django 5.0.7 on 2025-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscription_with_home_work"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersubscription",
            options={
                "verbose_name": "Подписка пользователя",
                "verbose_name_plural": "Подписки пользователей",
            },
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "canceled")], default="active", max_length=10
            ),
        ),
    ]
