# Generated by Django 5.0.7 on 2025-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_alter_usersubscription_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Активная"), ("canceled", "Отменена")],
                default="active",
                max_length=10,
            ),
        ),
    ]
