# Generated by Django 5.0.7 on 2025-05-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0012_alter_subscription_created_at_alter_subscription_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="expires_at",
        ),
    ]
