# Generated by Django 5.0.6 on 2024-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribtions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscribtion",
            name="purchased_before",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
