# Generated by Django 5.0.6 on 2024-06-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribtions", "0002_usersubscribtion_purchased_before"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscribtion",
            old_name="purchased_before",
            new_name="active_before",
        ),
        migrations.RemoveField(
            model_name="usersubscribtion",
            name="is_active",
        ),
    ]
