# Generated by Django 5.0.6 on 2024-06-09 12:41

import user.managers
import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=256)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
            bases=(models.Model, django.contrib.auth.models.PermissionManager),
            managers=[
                ("objects", user.managers.CustomUserManager()),
            ],
        ),
    ]
