# Generated by Django 5.2.1 on 2025-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Ник Telegram в формате @username",
                unique=True,
                verbose_name="Ник telegram",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(upload_to="avatar", verbose_name="Аватарка"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True, verbose_name="День рождения"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=120, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=True, verbose_name="Подтвержден"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Сотрудник"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=120, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="Пароль"),
        ),
    ]
