# Generated by Django 5.2.1 on 2025-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_telegram_alter_user_avatar_alter_user_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Ник Telegram в формате @username",
                null=True,
                unique=True,
                verbose_name="Ник telegram",
            ),
        ),
    ]
