# Generated by Django 5.0.6 on 2024-06-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_stuff",
        ),
    ]
