# Generated by Django 5.0.6 on 2024-07-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_user_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
    ]
