# Generated by Django 5.0.6 on 2024-07-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_remove_usersubscription_user"),
        ("user", "0008_remove_user_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.usersubscription",
            ),
        ),
    ]
