# Generated by Django 5.0.6 on 2024-07-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription",
        ),
    ]
