# Generated by Django 5.0.7 on 2025-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_jti",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
