# Generated by Django 5.0.7 on 2025-05-28 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="fingerprint",
            field=models.CharField(max_length=32, verbose_name="Отпечаток"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP-адресс"
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="jti",
            field=models.CharField(max_length=32, unique=True, verbose_name="JTI"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Время обновления"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User-Agent"),
        ),
    ]
