# Generated by Django 5.0.7 on 2025-05-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_created_at_alter_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active_jti",
        ),
    ]
