# Generated by Django 5.2.1 on 2025-05-29 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lessons", "0001_initial"),
        ("subscriptions", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscriptions",
            field=models.ManyToManyField(
                to="subscriptions.subscription", verbose_name="Подписки"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="tasks",
            field=models.ManyToManyField(to="tasks.task", verbose_name="Задачи"),
        ),
        migrations.AddField(
            model_name="lessonfile",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="userlesson",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lessons.lesson"
            ),
        ),
        migrations.AddField(
            model_name="userlesson",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddField(
            model_name="userlesson",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
