# Generated by Django 5.0.6 on 2024-06-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_userlesson_usertask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="answer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="answer",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
