# Generated by Django 5.0.6 on 2024-06-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_alter_task_answer_alter_usertask_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="answer",
            new_name="correct_answer",
        ),
    ]
