# Generated by Django 5.0.6 on 2024-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_rename_answer_task_correct_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlesson",
            name="is_tasks_completed",
            field=models.BooleanField(default=False),
        ),
    ]
