# Generated by Django 5.0.6 on 2024-06-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_userlesson_is_tasks_completed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="LessonTask",
        ),
        migrations.RenameModel(
            old_name="TaskFile",
            new_name="LessonTaskFile",
        ),
        migrations.RenameModel(
            old_name="UserTask",
            new_name="UserLessonTask",
        ),
        migrations.AlterModelTable(
            name="lessontask",
            table="lesson_task",
        ),
        migrations.AlterModelTable(
            name="lessontaskfile",
            table="lesson_task_file",
        ),
        migrations.AlterModelTable(
            name="userlessontask",
            table="user_lesson_task",
        ),
    ]
