# Generated by Django 5.0.6 on 2024-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_rename_task_lessontask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessontask",
            name="lesson",
        ),
    ]
