# Generated by Django 5.0.6 on 2024-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_remove_lessontask_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tasks",
            field=models.ManyToManyField(to="lessons.lessontask"),
        ),
    ]
