# Generated by Django 5.0.6 on 2024-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_lesson_tasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonTask",
            new_name="Task",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task",
        ),
    ]
