# Generated by Django 5.0.6 on 2024-06-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_rename_lessontask_task_alter_task_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LessonTaskFile",
            new_name="TaskFile",
        ),
        migrations.AlterModelTable(
            name="taskfile",
            table="task_file",
        ),
    ]
