# Generated by Django 5.0.6 on 2024-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0010_rename_lessontaskfile_taskfile_alter_taskfile_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskfile",
            name="name",
            field=models.CharField(default="First file", max_length=255),
            preserve_default=False,
        ),
    ]
