# Generated by Django 5.0.6 on 2024-06-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_taskfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlesson",
            name="complete_tasks_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 20, 13, 19, 44, 483271, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
