# Generated by Django 5.0.6 on 2024-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_userlesson_complete_tasks_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={"ordering": ("is_tasks_completed", "-is_completed", "created_at")},
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[("A", "Any"), ("T", "Table")], default="A", max_length=1
            ),
        ),
    ]
