# Generated by Django 5.0.6 on 2024-06-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0013_alter_userlesson_options_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="correct_answer",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="userlessontask",
            name="answer",
            field=models.JSONField(null=True),
        ),
    ]
