# Generated by Django 5.0.6 on 2024-06-30 08:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_alter_task_correct_answer_and_more"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": (
                    "is_closed",
                    "is_tasks_completed",
                    "-is_completed",
                    "created_at",
                )
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="opens_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 30, 8, 21, 10, 880532, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscribtion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="subscriptions.subscription",
            ),
        ),
    ]
