# Generated by Django 5.0.6 on 2024-06-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_alter_task_correct_answer_and_more"),
        ("subscribtions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": (
                    "is_closed",
                    "is_tasks_completed",
                    "-is_completed",
                    "created_at",
                )
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscribtion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="subscribtions.subscribtion",
            ),
        ),
    ]
