# Generated by Django 5.0.6 on 2024-06-29 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_alter_userlesson_options_lesson_subscribtion"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="opens_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 29, 15, 35, 58, 777256, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
