# Generated by Django 5.0.6 on 2024-06-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_alter_userlesson_options_lesson_opens_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="subscribtion",
            new_name="subscription",
        ),
    ]
