# Generated by Django 5.0.6 on 2024-07-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_rename_subscribtion_lesson_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="opens_at",
        ),
        migrations.AddField(
            model_name="lesson",
            name="depends_on",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lessons.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
