# Generated by Django 5.0.6 on 2024-07-03 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0017_remove_lesson_opens_at_lesson_depends_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="opens_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 3, 12, 51, 20, 819820, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
