# Generated by Django 5.0.6 on 2024-07-06 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0018_lesson_opens_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": (
                    "opens_at",
                    "is_tasks_completed",
                    "-is_completed",
                    "created_at",
                )
            },
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="depends_on",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="opens_at",
        ),
        migrations.RemoveField(
            model_name="userlesson",
            name="is_closed",
        ),
        migrations.AddField(
            model_name="userlesson",
            name="opens_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 6, 0, 7, 18, 346711, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
