# Generated by Django 5.0.6 on 2024-07-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0019_alter_userlesson_options_remove_lesson_depends_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="subscription",
        ),
    ]
