# Generated by Django 5.0.6 on 2024-07-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0020_remove_lesson_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": (
                    "opens_at",
                    "is_tasks_completed",
                    "-is_completed",
                    "created_at",
                ),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="userlessontask",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
    ]
