# Generated by Django 5.0.6 on 2024-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0021_alter_lesson_options_alter_task_options_and_more"),
        ("subscriptions", "0002_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="subscriptions",
            field=models.ManyToManyField(to="subscriptions.subscription"),
        ),
    ]
