# Generated by Django 5.0.6 on 2024-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0022_lesson_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlesson",
            name="complete_tasks_deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
