# Generated by Django 5.0.6 on 2024-07-19 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0023_alter_userlesson_complete_tasks_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlesson",
            name="complete_tasks_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 19, 21, 52, 45, 320417, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
