# Generated by Django 5.0.6 on 2024-07-21 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0024_alter_userlesson_complete_tasks_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complexity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
            preserve_default=False,
        ),
    ]
