# Generated by Django 5.0.6 on 2024-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0026_userlesson_result"),
        ("tasks", "0001_initial"),
        ("variants", "0012_alter_uservariant_tasks_alter_variant_tasks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlessontask",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskfile",
            name="task",
        ),
        migrations.RemoveField(
            model_name="userlessontask",
            name="lesson",
        ),
        migrations.AddField(
            model_name="userlesson",
            name="tasks",
            field=models.ManyToManyField(to="tasks.usertask"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="tasks",
            field=models.ManyToManyField(to="tasks.task"),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskFile",
        ),
        migrations.DeleteModel(
            name="UserLessonTask",
        ),
    ]
