# Generated by Django 5.0.6 on 2024-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0027_remove_userlessontask_task_remove_taskfile_task_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": ("opens_at", "status", "created_at"),
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RemoveField(
            model_name="userlesson",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="userlesson",
            name="is_skipped",
        ),
        migrations.RemoveField(
            model_name="userlesson",
            name="is_tasks_completed",
        ),
        migrations.AddField(
            model_name="userlesson",
            name="status",
            field=models.CharField(
                choices=[
                    (0, "not_started"),
                    (1, "started"),
                    (2, "completed"),
                    (3, "tasks_completed"),
                ],
                default="not_started",
                max_length=15,
            ),
        ),
    ]
