# Generated by Django 5.0.7 on 2024-07-27 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_alter_userlesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlesson',
            options={'ordering': ('lesson__opens_at', 'status', 'created_at'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='opens_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='opens_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 22, 58, 9, 535464, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
