# Generated by Django 5.0.7 on 2024-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0029_alter_userlesson_options_remove_userlesson_opens_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(default='videos/video.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
