# Generated by Django 5.0.7 on 2024-08-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0030_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='opens_at',
            field=models.DateField(),
        ),
    ]
