# Generated by Django 5.0.7 on 2024-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0031_alter_lesson_opens_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default='https://kinescope.io/embed/q7n78czSqqSUAwu49rHFXr'),
            preserve_default=False,
        ),
    ]
