# Generated by Django 5.0.7 on 2024-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_remove_lesson_video_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='kinescope_video_id',
            field=models.CharField(default='c33ecc17-f903-40cd-be28-d254f4f27bc3', max_length=64),
            preserve_default=False,
        ),
    ]
