# Generated by Django 5.0.6 on 2024-08-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0033_remove_lesson_video_url_lesson_kinescope_video_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="content",
            new_name="description",
        ),
    ]
