# Generated by Django 5.0.7 on 2024-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0034_rename_content_lesson_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlesson",
            options={
                "ordering": ("lesson__opens_at", "status", "created_at"),
                "verbose_name": "Урок пользователя",
                "verbose_name_plural": "Уроки пользователя",
            },
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="description",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "not_started"),
                    ("started", "started"),
                    ("completed", "completed"),
                    ("tasks_completed", "tasks_completed"),
                ],
                default="not_started",
                max_length=15,
            ),
        ),
    ]
