# Generated by Django 5.0.7 on 2024-12-12 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0035_alter_userlesson_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="files/lessons")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "lesson_file",
            },
        ),
    ]
