# Generated by Django 5.0.7 on 2025-02-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0036_lessonfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlesson",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="result",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userlesson",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
