# Generated by Django 5.0.7 on 2025-05-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0038_lesson_author"),
        ("subscriptions", "0010_alter_usersubscription_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="subscriptions",
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
    ]
