# Generated by Django 5.0.7 on 2025-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0040_remove_userlesson_result_remove_userlesson_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="kinescope_video_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
