# Generated by Django 5.0.7 on 2025-05-25 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0041_alter_lesson_kinescope_video_id"),
        ("subscriptions", "0010_alter_usersubscription_status"),
        ("tasks", "0012_alter_taskfile_options_task_name_alter_task_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonfile",
            options={
                "verbose_name": "Файл урока",
                "verbose_name_plural": "Файлы урока",
            },
        ),
        migrations.AlterField(
            model_name="lesson",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="kinescope_video_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор события в Kinescope. Создается автоматически после создания урока.",
                max_length=64,
                null=True,
                verbose_name="ID события Kinescope",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="opens_at",
            field=models.DateField(verbose_name="Когда открывается"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
                verbose_name="Подписка",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="tasks",
            field=models.ManyToManyField(to="tasks.task", verbose_name="Задачи"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="file",
            field=models.FileField(upload_to="files/lessons", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lessonfile",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
