# Generated by Django 5.0.7 on 2025-05-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0043_alter_lesson_created_at_alter_lesson_id_and_more"),
        ("subscriptions", "0013_remove_usersubscription_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="subscription",
        ),
        migrations.AddField(
            model_name="lesson",
            name="subscriptions",
            field=models.ManyToManyField(
                to="subscriptions.subscription", verbose_name="Подписка"
            ),
        ),
    ]
