# Generated by Django 5.0.7 on 2025-05-29 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0044_remove_lesson_subscription_lesson_subscriptions"),
        ("subscriptions", "0013_remove_usersubscription_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlesson",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.subscription",
            ),
        ),
    ]
